### ISSUE TITLE
NalSwitch crash when forbidden zero bit set

### ISSUE THREAD

**Issue by scottlamb** [dholroyd/h264-reader#19]
I saw you had a fuzz directory, which is pretty neat! I've been meaning to try fuzzing but never have.

I ran it, and it crashed almost immediately with this input: `[0, 0, 1, 221]`. Given how quickly it crashed, I suspect you've already seen this, but I thought I'd file the bug anyway.

`NalSwitch`'s `NalReader::push` implementation calls `NalHeader::new`. The latter is fallible (and failed). The former is infallible, so it calls `unwrap`, which of course crashes.

Should `NalReader:push` be fallible to handle this properly?

**Comment by dholroyd** [comment]
You are correct.  Apologies, I've got a fix locally that I had not committed.

The change doesn't make `NalReader::push()` fallible, but rather makes it ignore further input until `NalReader::start()` is next called.  My thinking: if `push()` could fail, the caller needs to come up with its own strategy for what to do with the rest of the input, which might just end up being the same (i.e. ignore data until the container provides a way to resynchronise).

It _is_ a problem that the caller doesn't have a mechanism to know about errors in the bitstream - true of this particular spot and also of problems in lots of other places of the codebase.  I don't have a design to address this lack of error reporting; maybe some kind of callback in the supplied `Ctx`.

**Comment by dholroyd** [comment]
(Also related to fuzzing - #20 - for which I don't yet have a fix.)
