### ISSUE TITLE
release

### ISSUE THREAD

**Issue by scottlamb** [dholroyd/h264-reader#21]
Could you please prepare a new release? I'd like to publish an initial version of [my RTSP crate](https://github.com/scottlamb/retina) to crates.io, and it depends on various things added since h264-reader 0.4.0 a year ago. Thanks!

**Comment by dholroyd** [comment]
Of course. I'll push 0.5.0 shortly.

**Comment by dholroyd** [comment]
Done!  https://crates.io/crates/h264-reader/0.5.0

**Comment by dholroyd** [comment]
Oh!  I hadn't spotted that you'd submitted #24 - I could have included that too, ah well :)

**Comment by scottlamb** [comment]
No worries. #24 is more a step toward #4 anyway that isn't especially important on its own.

Thanks for the release!
